# Generated by Django 4.2.16 on 2026-05-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="شماره تماس"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="موضوع")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "پیام تماس",
                "verbose_name_plural": "فرم تماس با ما",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام شرکت/سازمان"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="نام محصول مورد نظر"),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="تعداد/مقدار"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="توضیحات و مشخصات محصول"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "درخواست محصول",
                "verbose_name_plural": "فرم درخواست محصول",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام شرکت/سازمان"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ایمیل")),
                ("phone", models.CharField(max_length=20, verbose_name="شماره تماس")),
                (
                    "service_type",
                    models.CharField(max_length=200, verbose_name="نوع خدمت مورد نظر"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="توضیحات و جزئیات درخواست"),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ارسال"),
                ),
            ],
            options={
                "verbose_name": "درخواست خدمت",
                "verbose_name_plural": "فرم درخواست خدمات",
                "ordering": ["-created_at"],
            },
        ),
    ]
