# Generated by Django 4.2.16 on 2026-05-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="شماره تماس"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "footer_about",
                    models.TextField(blank=True, verbose_name="متن درباره ما (فوتر)"),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="اینستاگرام")),
                ("telegram", models.URLField(blank=True, verbose_name="تلگرام")),
                ("linkedin", models.URLField(blank=True, verbose_name="لینکدین")),
                ("twitter", models.URLField(blank=True, verbose_name="توییتر/ایکس")),
                ("youtube", models.URLField(blank=True, verbose_name="یوتیوب")),
                (
                    "whatsapp",
                    models.CharField(blank=True, max_length=30, verbose_name="واتساپ"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
    ]
