# Generated by Django 4.2.16 on 2026-05-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='آدرس چندزبانه'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='متن درباره ما چندزبانه'),
        ),
    ]
