# Generated by Django 4.2.16 on 2026-05-19 07:51

from django.db import migrations


def keep_persian_settings(apps, schema_editor):
    SiteSettings = apps.get_model('settings_app', 'SiteSettings')
    for settings in SiteSettings.objects.all():
        changed = False

        if not settings.address and isinstance(settings.address_i18n, dict):
            settings.address = settings.address_i18n.get('fa') or ''
            changed = True

        if not settings.footer_about and isinstance(settings.footer_about_i18n, dict):
            settings.footer_about = settings.footer_about_i18n.get('fa') or ''
            changed = True

        if changed:
            settings.save(update_fields=['address', 'footer_about'])


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_sitesettings_address_i18n_and_more'),
    ]

    operations = [
        migrations.RunPython(keep_persian_settings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address_i18n',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_about_i18n',
        ),
    ]
