# Generated by Django 4.2.16 on 2026-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        default="IconStar", max_length=100, verbose_name="نام آیکون"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان (فارسی)"),
                ),
                ("summary", models.TextField(verbose_name="خلاصه (فارسی)")),
                ("description", models.TextField(verbose_name="توضیحات (فارسی)")),
                (
                    "tags",
                    models.JSONField(default=list, verbose_name="تگ\u200cها (فارسی)"),
                ),
                (
                    "sections",
                    models.JSONField(
                        default=list,
                        help_text="آرایه\u200cای از {title, body}",
                        verbose_name="بخش\u200cها (فارسی)",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان (انگلیسی)"
                    ),
                ),
                (
                    "summary_en",
                    models.TextField(blank=True, verbose_name="خلاصه (انگلیسی)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات (انگلیسی)"),
                ),
                (
                    "tags_en",
                    models.JSONField(default=list, verbose_name="تگ\u200cها (انگلیسی)"),
                ),
                (
                    "sections_en",
                    models.JSONField(
                        default=list, verbose_name="بخش\u200cها (انگلیسی)"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="عنوان (عربی)"
                    ),
                ),
                (
                    "summary_ar",
                    models.TextField(blank=True, verbose_name="خلاصه (عربی)"),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="توضیحات (عربی)"),
                ),
                (
                    "tags_ar",
                    models.JSONField(default=list, verbose_name="تگ\u200cها (عربی)"),
                ),
                (
                    "sections_ar",
                    models.JSONField(default=list, verbose_name="بخش\u200cها (عربی)"),
                ),
                (
                    "highlight",
                    models.BooleanField(default=False, verbose_name="برجسته"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
