# Generated by Django 4.2.16 on 2026-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='توضیحات چندزبانه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='نمایش ویژه'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_key',
            field=models.CharField(blank=True, max_length=80, verbose_name='کلید آیکون'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sections',
            field=models.JSONField(blank=True, default=list, verbose_name='بخش\u200cهای توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='summary',
            field=models.TextField(blank=True, verbose_name='خلاصه'),
        ),
        migrations.AddField(
            model_name='service',
            name='summary_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='خلاصه چندزبانه'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='برچسب\u200cها'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='عنوان چندزبانه'),
        ),
    ]
