# Generated by Django 4.2.16 on 2026-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description_i18n_service_highlight_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'خدمت', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='icon_name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sections_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='sections_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='summary_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_en',
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
