# Generated by Django 4.2.16 on 2026-05-19 07:51

from django.db import migrations


def keep_persian_lists(apps, schema_editor):
    Service = apps.get_model('services', 'Service')
    for service in Service.objects.all():
        changed = False

        if isinstance(service.tags, dict):
            service.tags = service.tags.get('fa') or []
            changed = True

        if isinstance(service.sections, dict):
            service.sections = service.sections.get('fa') or []
            changed = True

        if changed:
            service.save(update_fields=['tags', 'sections'])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_remove_service_description_ar_and_more'),
    ]

    operations = [
        migrations.RunPython(keep_persian_lists, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='service',
            name='description_i18n',
        ),
        migrations.RemoveField(
            model_name='service',
            name='summary_i18n',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_i18n',
        ),
    ]
