# Generated by Django 4.2.16 on 2026-05-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subsidiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="subsidiaries/logos/",
                        verbose_name="لوگو",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="وبسایت")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
            ],
            options={
                "verbose_name": "زیرمجموعه",
                "verbose_name_plural": "زیرمجموعه\u200cهای هلدینگ",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
