# Generated by Django 4.2.16 on 2026-05-12 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subsidiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                ("monogram", models.CharField(max_length=10, verbose_name="مونوگرام")),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("blue", "آبی"),
                            ("rose", "گلبهی"),
                            ("violet", "بنفش"),
                            ("green", "سبز"),
                        ],
                        default="blue",
                        max_length=20,
                        verbose_name="تم رنگی",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام (فارسی)")),
                (
                    "tagline",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="شعار (فارسی)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیحات (فارسی)"),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام (انگلیسی)"
                    ),
                ),
                (
                    "tagline_en",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="شعار (انگلیسی)"
                    ),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="توضیحات (انگلیسی)"),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="نام (عربی)"
                    ),
                ),
                (
                    "tagline_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="شعار (عربی)"
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="توضیحات (عربی)"),
                ),
                ("website", models.URLField(blank=True, verbose_name="وبسایت")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="subsidiaries/logos/",
                        verbose_name="لوگو",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ ویرایش"),
                ),
            ],
            options={
                "verbose_name": "زیرمجموعه",
                "verbose_name_plural": "زیرمجموعه\u200cهای هلدینگ",
                "ordering": ["order", "created_at"],
            },
        ),
    ]
