# Generated by Django 4.2.16 on 2026-05-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='description_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='توضیحات چندزبانه'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='monogram',
            field=models.CharField(blank=True, max_length=20, verbose_name='مونوگرام'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='style',
            field=models.JSONField(blank=True, default=dict, verbose_name='تنظیمات ظاهری'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='tagline',
            field=models.JSONField(blank=True, default=dict, verbose_name='تگ\u200cلاین چندزبانه'),
        ),
    ]
