# Generated by Django 4.2.16 on 2026-05-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0002_subsidiary_description_i18n_subsidiary_monogram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='name_i18n',
            field=models.JSONField(blank=True, default=dict, verbose_name='نام چندزبانه'),
        ),
    ]
