# Generated by Django 4.2.16 on 2026-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0003_subsidiary_name_i18n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'زیرمجموعه', 'verbose_name_plural': 'زیرمجموعه\u200cهای هلدینگ'},
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='tagline_ar',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='theme',
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
