# Generated by Django 4.2.16 on 2026-05-19 07:51

from django.db import migrations, models


def keep_persian_values(apps, schema_editor):
    Subsidiary = apps.get_model('subsidiaries', 'Subsidiary')
    for subsidiary in Subsidiary.objects.all():
        changed = False

        if isinstance(subsidiary.tagline, dict):
            subsidiary.tagline = subsidiary.tagline.get('fa') or ''
            changed = True

        if not subsidiary.name and isinstance(subsidiary.name_i18n, dict):
            subsidiary.name = subsidiary.name_i18n.get('fa') or ''
            changed = True

        if not subsidiary.description and isinstance(subsidiary.description_i18n, dict):
            subsidiary.description = subsidiary.description_i18n.get('fa') or ''
            changed = True

        if changed:
            subsidiary.save(update_fields=['name', 'tagline', 'description'])


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0004_alter_subsidiary_options_and_more'),
    ]

    operations = [
        migrations.RunPython(keep_persian_values, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subsidiary',
            name='description_i18n',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='name_i18n',
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='tagline',
            field=models.CharField(blank=True, max_length=300, verbose_name='تگ\u200cلاین'),
        ),
    ]
