# Generated by Django 4.2.16 on 2026-05-19 13:25

from django.db import migrations, models
import django.db.models.deletion


def seed_department_categories(apps, schema_editor):
    DepartmentCategory = apps.get_model('subsidiaries', 'DepartmentCategory')
    Subsidiary = apps.get_model('subsidiaries', 'Subsidiary')

    education, _ = DepartmentCategory.objects.get_or_create(
        slug='education',
        defaults={
            'title': 'آموزشی',
            'description': '',
            'is_active': True,
            'order': 1,
        },
    )
    commerce, _ = DepartmentCategory.objects.get_or_create(
        slug='commerce',
        defaults={
            'title': 'بازرگانی',
            'description': '',
            'is_active': True,
            'order': 2,
        },
    )

    for subsidiary in Subsidiary.objects.all():
        style = subsidiary.style if isinstance(subsidiary.style, dict) else {}
        raw_department = str(style.get('department') or '').lower()
        haystack = f'{subsidiary.slug} {subsidiary.name} {subsidiary.tagline}'.lower()
        is_education = (
            raw_department in {'education', 'training'}
            or 'آموز' in raw_department
            or 'اموز' in raw_department
            or subsidiary.slug == 'media-med'
            or 'دوره' in haystack
            or 'آموز' in haystack
            or 'اموز' in haystack
        )
        subsidiary.department_category = education if is_education else commerce
        subsidiary.save(update_fields=['department_category'])


def clear_department_categories(apps, schema_editor):
    DepartmentCategory = apps.get_model('subsidiaries', 'DepartmentCategory')
    DepartmentCategory.objects.filter(slug__in=['education', 'commerce']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0005_remove_subsidiary_description_i18n_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی دپارتمان',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای دپارتمان',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='department_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subsidiaries', to='subsidiaries.departmentcategory', verbose_name='دسته\u200cبندی دپارتمان'),
        ),
        migrations.RunPython(seed_department_categories, clear_department_categories),
    ]
