# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsidiaries', '0006_departmentcategory_subsidiary_department_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiary',
            name='header_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='subsidiaries/headers/',
                verbose_name='تصویر هدر',
            ),
        ),
    ]
