# Generated by Django 4.2.16 on 2026-05-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subsidiaries", "0006_departmentcategory_subsidiary_department_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubsidiarySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "subsidiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="subsidiaries.subsidiary",
                        verbose_name="زیرمجموعه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بخش توضیحی",
                "verbose_name_plural": "بخش\u200cهای توضیحی",
                "ordering": ["order"],
            },
        ),
    ]
